!pip install numpy

In [1]:
!pip install numpy

In [2]:
!pip install pandas

In [3]:
import numpy as np
import pandas as pd

In [4]:
print(dir(np))

['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__array_api_version__', '__array_namespace_info__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_array_api_info', '_core', '_distributor_init', '_expired_attrs_2_0', '_get_promotion_state', '_globals', '_int_extended_msg', '_mat', '_msg', '_no_nep50_warning', '_pyinstaller_hooks_dir', '_pytesttester', '_set_promotion_state', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'arr

#Numpy means numerical operations to be done on numpy data structures.

#Arrays...n dimensional

#Arrays is the most important Data Structure in Numpy, Arrays are n-dimensionsal.

#Properties of Numpy DSA:

1) It is n-dimensional.

2) It stores homogenous data.

3) Broadcasting ops is allowed.(it is a very useful ops)

4) Vectorization(One-to-one mapping) is allowed.
 

In [5]:
a1=np.full((2,2),45)

In [6]:
print(a1)

[[45 45]
 [45 45]]


In [7]:
a1.dtype

dtype('int64')

In [8]:
a1.ndim

2

In [9]:
a1.size

4

In [10]:
a1.shape

(2, 2)

In [11]:
a1.nbytes

32

In [12]:

a2=np.full((2,2),45,dtype=np.int16)
a2.dtype


dtype('int16')

In [13]:
a2.nbytes

8

In [14]:
a3=np.full((2,2),'bhavik',dtype="str")
print(a3)

[['b' 'b']
 ['b' 'b']]


In [15]:
a3=np.full((2,2),'bhavik',dtype="object")
print(a3)

[['bhavik' 'bhavik']
 ['bhavik' 'bhavik']]


In [16]:
a4=np.full((2,2),'bhavik')
print(a4)

[['bhavik' 'bhavik']
 ['bhavik' 'bhavik']]


In [17]:
a4.nbytes


96

In [18]:
l = list(range(2, 10, 2))   # [2, 4, 6, 8]

# numpy array
ar1 = np.array(l)

print("List:", l)
print("Numpy Array:", ar1)

List: [2, 4, 6, 8]
Numpy Array: [2 4 6 8]


In [19]:
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.

In [20]:
np.arange(1, 10, 3) 

array([1, 4, 7])

In [21]:
np.linspace(1, 10, 3)

array([ 1. ,  5.5, 10. ])

In [22]:


# create 10 by 10 areray using random.randint method and find nuber of dublicate vlaues in that array u can use any method 


a1=np.random.randint(20,100,100)
a2=a1.reshape((10,10))
a2

array([[28, 38, 81, 50, 68, 85, 32, 95, 88, 84],
       [73, 35, 60, 85, 60, 72, 64, 42, 42, 42],
       [99, 69, 30, 46, 52, 99, 36, 88, 37, 64],
       [21, 80, 35, 45, 77, 83, 90, 42, 99, 23],
       [73, 67, 21, 26, 91, 80, 57, 76, 72, 79],
       [46, 43, 95, 43, 86, 39, 76, 46, 74, 95],
       [38, 46, 71, 98, 20, 22, 32, 56, 60, 88],
       [55, 89, 78, 24, 51, 55, 41, 83, 66, 47],
       [88, 35, 41, 27, 58, 68, 50, 89, 99, 83],
       [82, 37, 31, 86, 98, 22, 92, 59, 44, 66]], dtype=int32)

In [23]:
a1=a2.flatten()

In [24]:
print(a1)

[28 38 81 50 68 85 32 95 88 84 73 35 60 85 60 72 64 42 42 42 99 69 30 46
 52 99 36 88 37 64 21 80 35 45 77 83 90 42 99 23 73 67 21 26 91 80 57 76
 72 79 46 43 95 43 86 39 76 46 74 95 38 46 71 98 20 22 32 56 60 88 55 89
 78 24 51 55 41 83 66 47 88 35 41 27 58 68 50 89 99 83 82 37 31 86 98 22
 92 59 44 66]


In [25]:
s=set(a1)
print(s)

{np.int32(20), np.int32(21), np.int32(22), np.int32(23), np.int32(24), np.int32(26), np.int32(27), np.int32(28), np.int32(30), np.int32(31), np.int32(32), np.int32(35), np.int32(36), np.int32(37), np.int32(38), np.int32(39), np.int32(41), np.int32(42), np.int32(43), np.int32(44), np.int32(45), np.int32(46), np.int32(47), np.int32(50), np.int32(51), np.int32(52), np.int32(55), np.int32(56), np.int32(57), np.int32(58), np.int32(59), np.int32(60), np.int32(64), np.int32(66), np.int32(67), np.int32(68), np.int32(69), np.int32(71), np.int32(72), np.int32(73), np.int32(74), np.int32(76), np.int32(77), np.int32(78), np.int32(79), np.int32(80), np.int32(81), np.int32(82), np.int32(83), np.int32(84), np.int32(85), np.int32(86), np.int32(88), np.int32(89), np.int32(90), np.int32(91), np.int32(92), np.int32(95), np.int32(98), np.int32(99)}


In [26]:
len(list(a1))-len(s)

40

**indexing is for 1 d and for 2d we use slicing or sub setting 

In [28]:
a1 = np.random.randint(20, 100, 100)

a1 = a1[(a1 % 2 == 1) & (a1 % 3 == 0)]

print(a1)

[57 69 63 63 69 51 45 63 99 21 75 99 39 39 87 75 39 69 63 39 69 81 99]


In [29]:
a1=np.random.randint(1,100,25)
a1=a1.reshape((5,5))
a1


array([[91, 73, 33, 49, 28],
       [49, 85, 35, 92, 88],
       [98,  9, 15, 30, 16],
       [86, 23, 81, 51, 35],
       [71, 11,  5, 60, 83]], dtype=int32)

In [30]:
np.sum(a1,axis=0)    # columb wise sum 

array([395, 201, 169, 282, 250])

In [31]:
np.sum(a1,axis=1)    #row sum

array([274, 349, 168, 276, 230])

In [32]:
np.append?

Signature:       np.append(arr, values, axis=None)
Call signature:  np.append(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function append at 0x0000017C60764360>
File:            c:\users\lenovo\anaconda3\lib\site-packages\numpy\lib\_function_base_impl.py
Docstring:      
Append values to the end of an array.

Parameters
----------
arr : array_like
    Values are appended to a copy of this array.
values : array_like
    These values are appended to a copy of `arr`.  It must be of the
    correct shape (the same shape as `arr`, excluding `axis`).  If
    `axis` is not specified, `values` can be any shape and will be
    flattened before use.
axis : int, optional
    The axis along which `values` are appended.  If `axis` is not
    given, both `arr` and `values` are flattened before use.

Returns
-------
append : ndarray
    A copy of `arr` with `values` appended to `axis`.  Note that
    `append` does not occur in-place: a new array is allocated and
    f

a=np.arr([[10,20,30],[40,50,60],[70,80,90]])
a=np.append(

In [33]:
a=np.arange(10,91,10)
a=a.reshape((3,3))
a

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [34]:
np.append(a,[[100,110,120]],axis=0)      #this is vertical staking np.vstack?

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [36]:
a = np.array([[1],
              [2],
              [3]])

values = np.array([100,110,120])

valued = values.reshape((3,1))

result = np.append(a, valued, axis=1)

print(result)

[[  1 100]
 [  2 110]
 [  3 120]]


In [37]:
a=np.arange(10,91,10)
a=a.reshape((3,3))
a

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [38]:
np.append(a,[[100,110,120]],axis=0)

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])